### ISSUE TITLE
v15.0.0 eth_blockNumber Invalid Request

### ISSUE THREAD

**Issue by prettymuchbryce** [MetaMask/web3-provider-engine#311]
Starting in `v15.0.0` the following error occurs consistently:

```
Error: PollingBlockTracker - encountered an error while attempting to update latest block:
Error: Invalid request
    at ReconnectingWebsocketSubprovider._handleSocketMessage (websocket.js:174)
    at PollingBlockTracker._callee2$ (polling.js:135)
    at tryCatch (runtime.js:63)
    at Generator.invoke [as _invoke] (runtime.js:282)
    at Generator.prototype.(anonymous function) [as throw] (http://localhost:3000/static/js/0.chunk.js:47904:21)
    at asyncGeneratorStep (asyncToGenerator.js:3)
    at _throw (asyncToGenerator.js:29)
```

Web3 is polling the blockNumber with the request:

```json
{"id":1,"jsonrpc":"2.0","params":[],"method":"eth_blockNumber","skipCache":true}
```

The parity (v2.4.5) node is responding with

```json
{"jsonrpc":"2.0","error":{"code":-32600,"message":"Invalid request"},"id":1}
````

I don't see this `skipCache` flag documented anywhere in the Parity docs. Is this a standard property implemented in all Ethereum clients?

Prior to `v15.0.0` I don't see this `eth_blockNumber` request occurring at all. Just `eth_getBlockByNumber`.

**Comment by generalpiston** [comment]
https://github.com/MetaMask/eth-block-tracker/pull/39

**Comment by mikeshultz** [comment]
From what I'm told, Parity isn't a fan of the `skipCache` parameter.  I've added PR #316 to add an option to remove that parameter.

**Comment by leonprou** [comment]
We use Parity nodes and I see that error. Waiting for http://github.com/MetaMask/web3-provider-engine/pull/316 :)

**Comment by kumavis** [comment]
fixed in `eth-json-rpc-middleware@4.1.5` and `web3-provider-engine@15.0.2`

**Comment by sterlu** [comment]
Looks like `skipCache` is still being sent so this isn't fixed. 
Using web3-provider-engine@15.0.3 and eth-json-rpc-middleware@4.1.6

**Comment by deacix** [comment]
Hey guys! What are you doing?
https://github.com/MetaMask/web3-provider-engine/blob/8ee565e5acb33a424c42afd15c88639b06489f01/index.js#L134
You cannot set skipCache to true! On Parity nodes it is not working.

**Comment by BrendanChou** [comment]
Are you guys planning to look into this given reports of it still not being fixed?

**Comment by BrendanChou** [comment]
Still a problem in v15.0.6

**Comment by kumavis** [comment]
@BrendanChou for context, metamask no longer uses `web3-provider-engine` and so it is not maintained very closely.

**Comment by naiba** [comment]
Still a problem in v16.0.1
